LRQA-77350
AfonsoHSantos/liferay-portal pull request #134
Opened 2022-09-26 21:21 UTC by CaiocSiqueira

2022-09-26 21:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-26 21:22 UTC, CaiocSiqueira commented
ci:test:sf

2022-09-26 21:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/3423/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3423/jenkins-report.html">here</a>.</b></p>

2022-09-26 21:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78e2d90ddf637ae83e4063ed43b26756560083ec">78e2d90ddf637ae83e4063ed43b26756560083ec</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LRQA-77350">LRQA-77350</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/0f380b7fb67335e2c34ce20299f5bfe5f1a1cd51">0f380b7fb67335e2c34ce20299f5bfe5f1a1cd51</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3423/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3423/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase expected:&lt;...s";
     [java] 
     [java]   setUp \{
     [java]     task[ ("Log in Liferay Portal") \{
     [java]       TestCase.setUpPortalInstance();
     [java] 
     [java]       User.firstLoginPG();
     [java]     \}
     [java] 
     [java]     task ("Create a new page, a blog widget and a blog entry via API") \{
     [java]       JSONLayout.addPublicLayout(
     [java]         groupName = "Guest",
     [java]         layoutName = "Blogs Page");
     [java] 
     [java]       JSONLayout.addWidgetToPublicLayout(
     [java]         column = "1",
     [java]         groupName = "Guest",
     [java]         layoutName = "Blogs Page",
     [java]         widgetName = "Blogs");
     [java] 
     [java]       Navigator.gotoPage(pageName = "Blogs Page");
     [java] 
     [java]       JSONBlog.addEntry(
     [java]         entryContent = "Blogs Entry Content",
     [java]         entryTitle = "Blogs Entry Title");
     [java]     \}
     [java]   \}
     [java] 
     [java]   tearDown \{
     [java]     var testPortalInstance = PropsUtil.get("test.portal.instance");
     [java] 
     [java]     if ("\$\{testPortalInstance\}" == "true") \{
     [java]       PortalInstances.tearDownCP();
     [java]     \}
     [java]     else \{
     [java]       BlogsEntry.tearDownCP();
     [java] 
     [java]       Blogs.tearDownConfigurationDisplaySettingsPG(
     [java]         pageName = "Blogs Page",
     [java]         portletName = "Blogs");
     [java] 
     [java]       JSONLayout.deletePublicLayout(
     [java]         groupName = "Guest",
     [java]         layoutName = "Blogs Page");
     [java] 
     [java]       PagesAdmin.tearDownCP();
     [java]     \}
     [java]   \}
     [java] 
     [java]   @description = "Can Create a Blog"
     [java]   @priority = "5"
     [java]   test CanCreateBlog \{
     [java]     task ("create a new blog entry") \{
     [java]       Blogs.addEntry(
     [java]         entryContent = "UI Blogs Entry Content",
     [java]         entryTitle = "UI Blogs Entry Title");
     [java]     \}
     [java] 
     [java]     task ("validade that the blog entry was really created") \{
     [java]       BlogsEntry.viewPG(
     [java]         entryContent = "UI Blogs Entry Content",
     [java]         entryTitle = "UI Blogs Entry Title");
     [java]     \}
     [java]   \}]
     [java] 
     [java] \}&gt; but was:&lt;...s";
     [java] 
     [java]   setUp \{
     [java]     task[("Log in Liferay Portal")\{</pre></details></html>

2022-09-26 21:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3423/">test-portal-source-format#3423</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3423/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/AfonsoHSantos/liferay-portal/pull/134">AfonsoHSantos#134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1991146611">[master] ci:test:sf - CaiocSiqueira &gt; AfonsoHSantos - PR#134 - 2022-09-26[14:22:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/12484/">publish-testray-report#12484</a><br/></div></div>

2022-09-26 21:35 UTC, CaiocSiqueira commented
ci:test:sf

2022-09-26 21:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/3425/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3425/jenkins-report.html">here</a>.</b></p>

2022-09-26 21:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78e2d90ddf637ae83e4063ed43b26756560083ec">78e2d90ddf637ae83e4063ed43b26756560083ec</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LRQA-77350">LRQA-77350</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/a6b54d6664330b761c551b3dc08f4b0f10ccddc0">a6b54d6664330b761c551b3dc08f4b0f10ccddc0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3425/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3425/jenkins-report.html">here</a>.</h5></details></html>

2022-09-26 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3425/">test-portal-source-format#3425</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3425/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/AfonsoHSantos/liferay-portal/pull/134">AfonsoHSantos#134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1991160954">[master] ci:test:sf - CaiocSiqueira &gt; AfonsoHSantos - PR#134 - 2022-09-26[14:35:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/12598/">publish-testray-report#12598</a><br/></div></div>

2022-09-26 22:03 UTC, ViniLopes20 commented
Oi @CaiocSiqueira, seu teste está muito bom, mas a mensagem do commit tá SF, então você precisa colocar uma mensagem que diga o que você fez como a ação de adicionar o teste. Pode modificar?

2022-09-27 18:03 UTC, ViniLopes20 requested changes
Oi @CaiocSiqueira, falta você colocar as task no seu teste e no setUp

2022-09-27 20:51 UTC, CaiocSiqueira commented
ci:test:sf

2022-09-27 20:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3192/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3192/jenkins-report.html">here</a>.</b></p>

2022-09-27 20:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8faee93338fc2807062c1a76735cb71a7a42a0ef">8faee93338fc2807062c1a76735cb71a7a42a0ef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LRQA-77350">LRQA-77350</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/f4593f6ff5433e79553da6e417a3671c286937f2">f4593f6ff5433e79553da6e417a3671c286937f2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3192/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3192/jenkins-report.html">here</a>.</h5></details></html>

2022-09-27 20:55 UTC, ViniLopes20 approved these changes
Muito bom @CaiocSiqueira, obrigado por isso 😄

2022-09-27 20:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3192/">test-portal-source-format#3192</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3192/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/AfonsoHSantos/liferay-portal/pull/134">AfonsoHSantos#134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1992288128">[master] ci:test:sf - CaiocSiqueira &gt; AfonsoHSantos - PR#134 - 2022-09-27[13:51:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/12424/">publish-testray-report#12424</a><br/></div></div>

2022-09-27 21:06 UTC, AfonsoHSantos approved these changes
Muito bom @CaiocSiqueira! Parabéns ao time!

2022-09-27 21:06 UTC, closed without merging